#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.
# agent.dump_env()
temporal_address = "backend." + data.get("temporal_host")
host = data.get("host")
spotlight = {}
agent.write_envfile("spotlight.env", spotlight)
TEMPORAL_CORS_ORIGINS = f"https://{host}"
TEMPORAL_ADDRESS = temporal_address

temporal_ui = {
    "TEMPORAL_CORS_ORIGINS": TEMPORAL_CORS_ORIGINS,
    "TEMPORAL_ADDRESS": TEMPORAL_ADDRESS,
}
agent.write_envfile("temporal-ui.env", temporal_ui)

postiz_redis = {}
agent.write_envfile("postiz-redis.env", postiz_redis)

cluster_routing_allocation_disk_watermark_flood_stage = data.get(
    "cluster.routing.allocation.disk.watermark.flood_stage", "128mb"
)

discovery_type = data.get("discovery.type", "single-node")

es_java_opts = data.get("ES_JAVA_OPTS", "-Xms512m -Xmx512m")

xpack_security_enabled = data.get("xpack.security.enabled", "false")

cluster_routing_allocation_disk_threshold_enabled = data.get(
    "cluster.routing.allocation.disk.threshold_enabled", "true"
)

cluster_routing_allocation_disk_watermark_low = data.get(
    "cluster.routing.allocation.disk.watermark.low", "512mb"
)

cluster_routing_allocation_disk_watermark_high = data.get(
    "cluster.routing.allocation.disk.watermark.high", "256mb"
)

temporal_elasticsearch = {
    "cluster.routing.allocation.disk.watermark.flood_stage": cluster_routing_allocation_disk_watermark_flood_stage,
    "discovery.type": discovery_type,
    "ES_JAVA_OPTS": es_java_opts,
    "xpack.security.enabled": xpack_security_enabled,
    "cluster.routing.allocation.disk.threshold_enabled": cluster_routing_allocation_disk_threshold_enabled,
    "cluster.routing.allocation.disk.watermark.low": cluster_routing_allocation_disk_watermark_low,
    "cluster.routing.allocation.disk.watermark.high": cluster_routing_allocation_disk_watermark_high,
}

agent.write_envfile("temporal-elasticsearch.env", temporal_elasticsearch)


temporal_admin_tools = {
    "TEMPORAL_ADDRESS": TEMPORAL_ADDRESS,
    "TEMPORAL_CLI_ADDRESS": TEMPORAL_ADDRESS,
}
agent.write_envfile("temporal-admin-tools.env", temporal_admin_tools)

IS_GENERAL = data.get("IS_GENERAL", "true")
NEXT_PUBLIC_UPLOAD_DIRECTORY = data.get("NEXT_PUBLIC_UPLOAD_DIRECTORY", "/uploads")
GITHUB_CLIENT_SECRET = data.get("GITHUB_CLIENT_SECRET", "")
BEEHIIVE_API_KEY = data.get("BEEHIIVE_API_KEY", "")
YOUTUBE_CLIENT_ID = data.get("YOUTUBE_CLIENT_ID", "")
DRIBBBLE_CLIENT_ID = data.get("DRIBBBLE_CLIENT_ID", "")
FACEBOOK_APP_SECRET = data.get("FACEBOOK_APP_SECRET", "")
STORAGE_PROVIDER = data.get("STORAGE_PROVIDER", "local")
X_API_KEY = data.get("X_API_KEY", "")
THREADS_APP_SECRET = data.get("THREADS_APP_SECRET", "")
TIKTOK_CLIENT_SECRET = data.get("TIKTOK_CLIENT_SECRET", "")
SLACK_SECRET = data.get("SLACK_SECRET", "")
MAIN_URL = f"https://{host}"
LINKEDIN_CLIENT_SECRET = data.get("LINKEDIN_CLIENT_SECRET", "")
SLACK_SIGNING_SECRET = data.get("SLACK_SIGNING_SECRET", "")
MASTODON_URL = data.get("MASTODON_URL", "https://mastodon.social")
MASTODON_CLIENT_SECRET = data.get("MASTODON_CLIENT_SECRET", "")
NEXT_PUBLIC_POLOTNO = data.get("NEXT_PUBLIC_POLOTNO", "")
STRIPE_SIGNING_KEY = data.get("STRIPE_SIGNING_KEY", "")
BACKEND_INTERNAL_URL = f"https://{host}"
BEEHIIVE_PUBLICATION_ID = data.get("BEEHIIVE_PUBLICATION_ID", "")
PINTEREST_CLIENT_ID = data.get("PINTEREST_CLIENT_ID", "")
DRIBBBLE_CLIENT_SECRET = data.get("DRIBBBLE_CLIENT_SECRET", "")
SLACK_ID = data.get("SLACK_ID", "")
NEXT_PUBLIC_DISCORD_SUPPORT = data.get("NEXT_PUBLIC_DISCORD_SUPPORT", "")
GITHUB_CLIENT_ID = data.get("GITHUB_CLIENT_ID", "")
DISCORD_CLIENT_SECRET = data.get("DISCORD_CLIENT_SECRET", "")
OPENAI_API_KEY = data.get("OPENAI_API_KEY", "")
NEXT_PUBLIC_BACKEND_URL = f"https://{host}/api"
DISABLE_REGISTRATION = data.get("DISABLE_REGISTRATION", "false")
RUN_CRON = data.get("RUN_CRON", "true")
REDDIT_CLIENT_SECRET = data.get("REDDIT_CLIENT_SECRET", "")
FEE_AMOUNT = data.get("FEE_AMOUNT", "0.05")
NX_ADD_PLUGINS = data.get("NX_ADD_PLUGINS", "false")
FRONTEND_URL = f"https://{host}"
LINKEDIN_CLIENT_ID = data.get("LINKEDIN_CLIENT_ID", "")
THREADS_APP_ID = data.get("THREADS_APP_ID", "")
FACEBOOK_APP_ID = data.get("FACEBOOK_APP_ID", "")
YOUTUBE_CLIENT_SECRET = data.get("YOUTUBE_CLIENT_SECRET", "")
TIKTOK_CLIENT_ID = data.get("TIKTOK_CLIENT_ID", "")
PINTEREST_CLIENT_SECRET = data.get("PINTEREST_CLIENT_SECRET", "")
MASTODON_CLIENT_ID = data.get("MASTODON_CLIENT_ID", "")
X_API_SECRET = data.get("X_API_SECRET", "")
REDDIT_CLIENT_ID = data.get("REDDIT_CLIENT_ID", "")
DISCORD_CLIENT_ID = data.get("DISCORD_CLIENT_ID", "")
DISCORD_BOT_TOKEN_ID = data.get("DISCORD_BOT_TOKEN_ID", "")
API_LIMIT = data.get("API_LIMIT", "30")
STRIPE_PUBLISHABLE_KEY = data.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = data.get("STRIPE_SECRET_KEY", "")
STRIPE_SIGNING_KEY_CONNECT = data.get("STRIPE_SIGNING_KEY_CONNECT", "")

postiz = {
    "TEMPORAL_ADDRESS": "temporal-app:7233",
    "IS_GENERAL": IS_GENERAL,
    "NEXT_PUBLIC_UPLOAD_DIRECTORY": NEXT_PUBLIC_UPLOAD_DIRECTORY,
    "GITHUB_CLIENT_SECRET": GITHUB_CLIENT_SECRET,
    "BEEHIIVE_API_KEY": BEEHIIVE_API_KEY,
    "YOUTUBE_CLIENT_ID": YOUTUBE_CLIENT_ID,
    "DRIBBBLE_CLIENT_ID": DRIBBBLE_CLIENT_ID,
    "FACEBOOK_APP_SECRET": FACEBOOK_APP_SECRET,
    "STORAGE_PROVIDER": STORAGE_PROVIDER,
    "X_API_KEY": X_API_KEY,
    "THREADS_APP_SECRET": THREADS_APP_SECRET,
    "TIKTOK_CLIENT_SECRET": TIKTOK_CLIENT_SECRET,
    "SLACK_SECRET": SLACK_SECRET,
    "MAIN_URL": MAIN_URL,
    "LINKEDIN_CLIENT_SECRET": LINKEDIN_CLIENT_SECRET,
    "SLACK_SIGNING_SECRET": SLACK_SIGNING_SECRET,
    "MASTODON_URL": MASTODON_URL,
    "MASTODON_CLIENT_SECRET": MASTODON_CLIENT_SECRET,
    "NEXT_PUBLIC_POLOTNO": NEXT_PUBLIC_POLOTNO,
    "STRIPE_SIGNING_KEY": STRIPE_SIGNING_KEY,
    "BACKEND_INTERNAL_URL": BACKEND_INTERNAL_URL,
    "BEEHIIVE_PUBLICATION_ID": BEEHIIVE_PUBLICATION_ID,
    "PINTEREST_CLIENT_ID": PINTEREST_CLIENT_ID,
    "DRIBBBLE_CLIENT_SECRET": DRIBBBLE_CLIENT_SECRET,
    "SLACK_ID": SLACK_ID,
    "NEXT_PUBLIC_DISCORD_SUPPORT": NEXT_PUBLIC_DISCORD_SUPPORT,
    "GITHUB_CLIENT_ID": GITHUB_CLIENT_ID,
    "DISCORD_CLIENT_SECRET": DISCORD_CLIENT_SECRET,
    "OPENAI_API_KEY": OPENAI_API_KEY,
    "NEXT_PUBLIC_BACKEND_URL": NEXT_PUBLIC_BACKEND_URL,
    "DISABLE_REGISTRATION": DISABLE_REGISTRATION,
    "RUN_CRON": RUN_CRON,
    "REDDIT_CLIENT_SECRET": REDDIT_CLIENT_SECRET,
    "FEE_AMOUNT": FEE_AMOUNT,
    "NX_ADD_PLUGINS": NX_ADD_PLUGINS,
    "FRONTEND_URL": FRONTEND_URL,
    "LINKEDIN_CLIENT_ID": LINKEDIN_CLIENT_ID,
    "THREADS_APP_ID": THREADS_APP_ID,
    "FACEBOOK_APP_ID": FACEBOOK_APP_ID,
    "YOUTUBE_CLIENT_SECRET": YOUTUBE_CLIENT_SECRET,
    "TIKTOK_CLIENT_ID": TIKTOK_CLIENT_ID,
    "PINTEREST_CLIENT_SECRET": PINTEREST_CLIENT_SECRET,
    "MASTODON_CLIENT_ID": MASTODON_CLIENT_ID,
    "X_API_SECRET": X_API_SECRET,
    "REDDIT_CLIENT_ID": REDDIT_CLIENT_ID,
    "DISCORD_CLIENT_ID": DISCORD_CLIENT_ID,
    "DISCORD_BOT_TOKEN_ID": DISCORD_BOT_TOKEN_ID,
    "API_LIMIT": API_LIMIT,
    "STRIPE_PUBLISHABLE_KEY": STRIPE_PUBLISHABLE_KEY,
    "STRIPE_SECRET_KEY": STRIPE_SECRET_KEY,
    "STRIPE_SIGNING_KEY_CONNECT": STRIPE_SIGNING_KEY_CONNECT,
}
agent.write_envfile("postiz.env", postiz)
