#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup default values
host = data.get("host")
h2hs = data.get("http2https", True)
le = data.get("lets_encrypt", False)
temporal_host = data.get("temporal_host")
env_tcp_ports = os.environ["TCP_PORTS"].split(",")

frontend = env_tcp_ports[0]
temporal_ui = env_tcp_ports[1]
postiz_backend = env_tcp_ports[2]

agent.set_env("POSTIZ_PORT", frontend)
agent.set_env("TEMPORAL_UI_PORT", temporal_ui)
agent.set_env("POSTIZ_BACKEND_PORT", postiz_backend)

# Setup configuration from user input.
agent.set_env("TRAEFIK_HOST", host)
agent.set_env("TRAEFIK_HTTP2HTTPS", h2hs)
agent.set_env("TRAEFIK_LETS_ENCRYPT", le)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id("traefik@node")
if default_traefik_id is None:
    sys.exit(2)

response = agent.tasks.run(
    agent_id=agent.resolve_agent_id("traefik@node"),
    action="set-route",
    data={
        "instance": os.environ["MODULE_ID"],
        "url": "http://127.0.0.1:" + frontend,
        "host": host,
        "http2https": h2hs,
        "lets_encrypt": le,
    },
)
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id("traefik@node"),
    action="set-route",
    data={
        "instance": os.environ["MODULE_ID"] + "-temporal-ui",
        "url": "http://127.0.0.1:" + temporal_ui,
        "host": temporal_host,
        "http2https": h2hs,
        "lets_encrypt": le,
    },
)
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id("traefik@node"),
    action="set-route",
    data={
        "instance": os.environ["MODULE_ID"] + "-postiz-backend",
        "url": "http://127.0.0.1:" + postiz_backend,
        "host": "api." + temporal_host,
        "http2https": h2hs,
        "lets_encrypt": le,
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response["exit_code"] == 0)
