#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# just before starting systemd unit
# agent.dump_env()
POSTGRES_PASSWORD = data.get("POSTGRES_PASSWORD", "postiz-password") 
POSTGRES_USER = data.get("POSTGRES_USER", "postiz-user") 
POSTGRES_DB = data.get("POSTGRES_DB", "postiz-db-local") 
 
postiz-postgres = { 
 "POSTGRES_PASSWORD" : POSTGRES_PASSWORD ,
 "POSTGRES_USER" : POSTGRES_USER ,
 "POSTGRES_DB" : POSTGRES_DB ,
} 
agent.write_envfile("postiz-postgres.env", postiz-postgres) 
