#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# just before starting systemd unit
# agent.dump_env()
POSTGRES_PASSWORD = generate_random_password(12)
POSTGRES_USER = data.get("POSTGRES_USER", "postiz-user")
POSTGRES_DB = data.get("POSTGRES_DB", "postiz-db-local")

postiz_postgres = {
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_DB": POSTGRES_DB,
}
agent.write_envfile("postiz-postgres.env", postiz_postgres)
POSTGRES_PASSWORD_TEMPORAL = generate_random_password(12)
POSTGRES_USER_TEMPORAL = data.get("POSTGRES_USER", "temporal")

temporal_postgresql = {
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD_TEMPORAL,
    "POSTGRES_USER": POSTGRES_USER_TEMPORAL,
    "POSTGRES_SEEDS": "postiz-postgres-app",
}
agent.write_envfile("temporal-postgresql.env", temporal_postgresql)
temporal = {
    "DB": "postgres12",
    "POSTGRES_PWD": POSTGRES_PASSWORD_TEMPORAL,
    "ES_SEEDS": "temporal-elasticsearch-app.service",
    "ES_VERSION": "v7",
    "TEMPORAL_NAMESPACE": "default",
    "DB_PORT": "5432",
    "POSTGRES_USER": POSTGRES_USER_TEMPORAL,
    "POSTGRES_SEEDS": "postiz-postgres-app",
    "ENABLE_ES": "true",
}
agent.write_envfile("temporal.env", temporal)

JWT_SECRET = generate_random_password(64)
UPLOAD_DIRECTORY = data.get("UPLOAD_DIRECTORY", "/uploads")
REDIS_URL = data.get("REDIS_URL", "redis://postiz-redis-app:6379")
DATABASE_URL = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postiz-postgres-app:5432/{POSTGRES_DB}",
)
postiz = {
    "JWT_SECRET": JWT_SECRET,
    "DATABASE_URL": DATABASE_URL,
    "UPLOAD_DIRECTORY": UPLOAD_DIRECTORY,
    "REDIS_URL": REDIS_URL,
}
agent.write_envfile("postiz_app.env", postiz)
